import platform

SYSTEM_OS = platform.system().lower()
if SYSTEM_OS == "darwin":
    SYSTEM_OS = "mac"

TOOL_CATEGORIES = {
    "git": "Core",
    "python": "Runtime",
    "node": "Runtime",
    "go": "Runtime",
    "rustc": "Runtime",
    "java": "Runtime",
    "ruby": "Runtime",
    "php": "Runtime",
    "dotnet": "Runtime",
    "gcc": "Core",
    "yarn": "Package Manager",
    "pnpm": "Package Manager",
    "bun": "Runtime",
    "mvn": "Package Manager",
    "gradle": "Package Manager",
    "pip": "Package Manager",
    "npm": "Package Manager",
    "cargo": "Package Manager",
    "gem": "Package Manager",
    "docker": "Containers",
    "kubectl": "Kubernetes",
    "helm": "Kubernetes",
    "terraform": "DevOps",
    "aws": "Cloud",
    "gcloud": "Cloud",
    "az": "Cloud",
    "supabase": "Backend",
    "heroku": "Cloud",
    "firebase": "Backend",
    "vercel": "Cloud",
    "netlify": "Cloud",
    "gh": "Core",
    "flutter": "Mobile",
    "dart": "Mobile",
    "psql": "Database",
    "mysql": "Database",
    "mongosh": "Database",
    "sqlite3": "Database",
    "redis": "Database",
    "redis-cli": "Database",
    "jq": "Utility",
    "wget": "Utility",
    "curl": "Utility",
    "cmake": "Utility",
    "make": "Utility",
}

TOOL_METADATA = {
    "windows": {
        "git": "Git.Git",
        "python": "Python.Python.3",
        "node": "OpenJS.NodeJS",
        "go": "GoLang.Go",
        "rustc": "Rustlang.Rustup",
        "java": "Microsoft.OpenJDK.21",
        "ruby": "RubyInstallerTeam.Ruby",
        "php": "PHP.PHP",
        "dotnet": "Microsoft.DotNet.SDK.8",
        "gcc": "msys2.mingw-w64-gcc",
        "yarn": "Yarn.Yarn",
        "pnpm": "pnpm.pnpm",
        "bun": "Oven-sh.Bun",
        "mvn": "Apache.Maven",
        "gradle": "Gradle.Gradle",
        "docker": "Docker.DockerDesktop",
        "kubectl": "Kubernetes.kubectl",
        "helm": "Helm.Helm",
        "terraform": "Hashicorp.Terraform",
        "aws": "Amazon.AWSCLI",
        "gcloud": "Google.CloudSDK",
        "az": "Microsoft.AzureCLI",
        "supabase": "Supabase.CLI",
        "heroku": "Heroku.CLI",
        "gh": "GitHub.cli",
        "flutter": "Flutter.Flutter",
        "dart": "Dart.DartSDK",
        "psql": "PostgreSQL.PostgreSQL",
        "mysql": "Oracle.MySQL",
        "mongosh": "MongoDB.Shell",
        "sqlite3": "SQLite.SQLite",
        "redis": "Redis.Redis",
        "jq": "jqlang.jq",
        "wget": "GNU.Wget",
        "curl": "curl.curl",
        "cmake": "Kitware.CMake",
        "make": "ezwinports.make",
    },
    "mac": {
        "git": "git",
        "python": "python3",
        "node": "node",
        "go": "go",
        "rustc": "rustup-init",
        "java": "openjdk",
        "ruby": "ruby",
        "php": "php",
        "dotnet": "dotnet",
        "gcc": "gcc",
        "yarn": "yarn",
        "pnpm": "pnpm",
        "bun": "bun",
        "mvn": "maven",
        "gradle": "gradle",
        "docker": "docker",
        "kubectl": "kubernetes-cli",
        "helm": "helm",
        "terraform": "terraform",
        "aws": "awscli",
        "gcloud": "google-cloud-sdk",
        "az": "azure-cli",
        "supabase": "supabase/tap/supabase",
        "heroku": "heroku/tap/heroku",
        "gh": "gh",
        "flutter": "flutter",
        "dart": "dart",
        "psql": "postgresql",
        "mysql": "mysql",
        "mongosh": "mongosh",
        "sqlite3": "sqlite",
        "redis": "redis",
        "jq": "jq",
        "wget": "wget",
        "curl": "curl",
        "cmake": "cmake",
        "make": "make",
    },
    "linux": {
        "git": "git",
        "python": "python3",
        "node": "nodejs",
        "go": "golang-go",
        "rustc": "rustc",
        "java": "default-jdk",
        "ruby": "ruby-full",
        "php": "php",
        "dotnet": "dotnet-sdk-8.0",
        "gcc": "gcc",
        "yarn": "yarnpkg",
        "pnpm": "pnpm",
        "mvn": "maven",
        "gradle": "gradle",
        "docker": "docker.io",
        "kubectl": "kubectl",
        "helm": "helm",
        "terraform": "terraform",
        "aws": "awscli",
        "az": "azure-cli",
        "gh": "gh",
        "psql": "postgresql-client",
        "mysql": "mysql-client",
        "sqlite3": "sqlite3",
        "redis": "redis-tools",
        "jq": "jq",
        "wget": "wget",
        "curl": "curl",
        "cmake": "cmake",
        "make": "make",
    },
}

VERSION_COMMANDS = {
    "git": {
        "windows": ["git", "--version"],
        "linux": ["git", "--version"],
        "mac": ["git", "--version"],
    },
    "python": {
        "windows": ["python", "--version"],
        "linux": ["python3", "--version"],
        "mac": ["python3", "--version"],
    },
    "node": {
        "windows": ["node", "--version"],
        "linux": ["node", "--version"],
        "mac": ["node", "--version"],
    },
    "go": {
        "windows": ["go", "version"],
        "linux": ["go", "version"],
        "mac": ["go", "version"],
    },
    "rustc": {
        "windows": ["rustc", "--version"],
        "linux": ["rustc", "--version"],
        "mac": ["rustc", "--version"],
    },
    "java": {
        "windows": ["java", "-version"],
        "linux": ["java", "-version"],
        "mac": ["java", "-version"],
    },
    "javac": {
        "windows": ["javac", "-version"],
        "linux": ["javac", "-version"],
        "mac": ["javac", "-version"],
    },
    "ruby": {
        "windows": ["ruby", "--version"],
        "linux": ["ruby", "--version"],
        "mac": ["ruby", "--version"],
    },
    "php": {
        "windows": ["php", "--version"],
        "linux": ["php", "--version"],
        "mac": ["php", "--version"],
    },
    "dotnet": {
        "windows": ["dotnet", "--version"],
        "linux": ["dotnet", "--version"],
        "mac": ["dotnet", "--version"],
    },
    "gcc": {
        "windows": ["gcc", "--version"],
        "linux": ["gcc", "--version"],
        "mac": ["gcc", "--version"],
    },
    "dart": {
        "windows": ["dart", "--version"],
        "linux": ["dart", "--version"],
        "mac": ["dart", "--version"],
    },
    "pip": {
        "windows": ["pip", "--version"],
        "linux": ["pip3", "--version"],
        "mac": ["pip3", "--version"],
    },
    "npm": {
        "windows": ["npm", "--version"],
        "linux": ["npm", "--version"],
        "mac": ["npm", "--version"],
    },
    "yarn": {
        "windows": ["yarn", "--version"],
        "linux": ["yarn", "--version"],
        "mac": ["yarn", "--version"],
    },
    "pnpm": {
        "windows": ["pnpm", "--version"],
        "linux": ["pnpm", "--version"],
        "mac": ["pnpm", "--version"],
    },
    "bun": {
        "windows": ["bun", "--version"],
        "linux": ["bun", "--version"],
        "mac": ["bun", "--version"],
    },
    "cargo": {
        "windows": ["cargo", "--version"],
        "linux": ["cargo", "--version"],
        "mac": ["cargo", "--version"],
    },
    "mvn": {
        "windows": ["mvn", "--version"],
        "linux": ["mvn", "--version"],
        "mac": ["mvn", "--version"],
    },
    "gradle": {
        "windows": ["gradle", "--version"],
        "linux": ["gradle", "--version"],
        "mac": ["gradle", "--version"],
    },
    "gem": {
        "windows": ["gem", "--version"],
        "linux": ["gem", "--version"],
        "mac": ["gem", "--version"],
    },
    "docker": {
        "windows": ["docker", "--version"],
        "linux": ["docker", "--version"],
        "mac": ["docker", "--version"],
    },
    "kubectl": {
        "windows": ["kubectl", "version", "--client"],
        "linux": ["kubectl", "version", "--client"],
        "mac": ["kubectl", "version", "--client"],
    },
    "helm": {
        "windows": ["helm", "version"],
        "linux": ["helm", "version"],
        "mac": ["helm", "version"],
    },
    "terraform": {
        "windows": ["terraform", "version"],
        "linux": ["terraform", "version"],
        "mac": ["terraform", "version"],
    },
    "aws": {
        "windows": ["aws", "--version"],
        "linux": ["aws", "--version"],
        "mac": ["aws", "--version"],
    },
    "gcloud": {
        "windows": ["gcloud", "--version"],
        "linux": ["gcloud", "--version"],
        "mac": ["gcloud", "--version"],
    },
    "az": {
        "windows": ["az", "--version"],
        "linux": ["az", "--version"],
        "mac": ["az", "--version"],
    },
    "supabase": {
        "windows": ["supabase", "--version"],
        "linux": ["supabase", "--version"],
        "mac": ["supabase", "--version"],
    },
    "firebase": {
        "windows": ["firebase", "--version"],
        "linux": ["firebase", "--version"],
        "mac": ["firebase", "--version"],
    },
    "vercel": {
        "windows": ["vercel", "--version"],
        "linux": ["vercel", "--version"],
        "mac": ["vercel", "--version"],
    },
    "netlify": {
        "windows": ["netlify", "--version"],
        "linux": ["netlify", "--version"],
        "mac": ["netlify", "--version"],
    },
    "gh": {
        "windows": ["gh", "--version"],
        "linux": ["gh", "--version"],
        "mac": ["gh", "--version"],
    },
    "flutter": {
        "windows": ["flutter", "--version"],
        "linux": ["flutter", "--version"],
        "mac": ["flutter", "--version"],
    },
    "psql": {
        "windows": ["psql", "--version"],
        "linux": ["psql", "--version"],
        "mac": ["psql", "--version"],
    },
    "mysql": {
        "windows": ["mysql", "--version"],
        "linux": ["mysql", "--version"],
        "mac": ["mysql", "--version"],
    },
    "mongosh": {
        "windows": ["mongosh", "--version"],
        "linux": ["mongosh", "--version"],
        "mac": ["mongosh", "--version"],
    },
    "sqlite3": {
        "windows": ["sqlite3", "--version"],
        "linux": ["sqlite3", "--version"],
        "mac": ["sqlite3", "--version"],
    },
    "redis-cli": {
        "windows": ["redis-cli", "--version"],
        "linux": ["redis-cli", "--version"],
        "mac": ["redis-cli", "--version"],
    },
    "jq": {
        "windows": ["jq", "--version"],
        "linux": ["jq", "--version"],
        "mac": ["jq", "--version"],
    },
    "wget": {
        "windows": ["wget", "--version"],
        "linux": ["wget", "--version"],
        "mac": ["wget", "--version"],
    },
    "curl": {
        "windows": ["curl", "--version"],
        "linux": ["curl", "--version"],
        "mac": ["curl", "--version"],
    },
    "cmake": {
        "windows": ["cmake", "--version"],
        "linux": ["cmake", "--version"],
        "mac": ["cmake", "--version"],
    },
    "make": {
        "windows": ["make", "--version"],
        "linux": ["make", "--version"],
        "mac": ["make", "--version"],
    },
}

DEPENDENCY_TOOLS = {
    "pip": "python",
    "npm": "node",
    "yarn": "node",
    "pnpm": "node",
    "cargo": "rustc",
    "gem": "ruby",
    "javac": "java",
    "firebase": "node",
    "vercel": "node",
    "netlify": "node",
}
